stages:
  clean_data:
    cmd: python src/data/clean_data.py data/raw/smoking_driking_dataset_Ver01.csv data/interim/cleaned_data.csv
    deps:
      - data/raw/smoking_driking_dataset_Ver01.csv
      - src/data/clean_data.py
    outs:
      - data/interim/cleaned_data.csv

  one_hot_encode_data:
    cmd: python src/data/encode_data.py data/interim/cleaned_data.csv data/processed/processed_data.csv
    deps:
      - data/interim/cleaned_data.csv
      - src/data/encode_data.py
    outs:
      - data/processed/processed_data.csv

  prepare_datasets:
    cmd: python src/models/prepare_datasets.py data/processed/processed_data.csv data/processed/train.csv data/processed/val.csv
    deps:
      - data/processed/processed_data.csv
      - src/models/prepare_datasets.py
    outs:
      - data/processed/train.csv
      - data/processed/val.csv

  train_model:
    cmd: python src/models/train_model.py data/processed/train.csv data/processed/val.csv reports/metrics.json models/model.clf
    deps:
      - data/processed/val.csv
      - data/processed/train.csv
      - src/models/train_model.py
    outs:
      - models/model.clf
      - reports/metrics.json

