stages:
  convert_json_to_txt:
    cmd: python src/data/convert_json_to_txt.py data/raw/all_scripts_raw.json data/interim/all_scripts_raw.txt
    deps:
      - data/raw/all_scripts_raw.json
      - src/data/convert_json_to_txt.py
    outs:
      - data/interim/all_scripts_raw.txt
